import Navigation from "../components/Navigation";
import Fusszeile from "../components/Fusszeile";
import Head from "next/head";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Deluxe Coffee - Der Lieferdienst</title>
        <meta name="description" content="Generated by Christian S." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      {children}
      <Fusszeile />
    </>
  );
}
